# use Docker-based container (instead of OpenVZ)
sudo: false

os:
  - linux

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y docker.io

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - cd test-project && sbt  ++$TRAVIS_SCALA_VERSION  launch-containers && sbt ++$TRAVIS_SCALA_VERSION  stop-containers && cd -

scala:
  - 2.10.4

jdk:
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - slim@tebourbi.com
    - stephane.jeandeaux@gmail.com
    - david_ravet@carrefour.com
